chore(deps): update dependency knip to v5.34.0 (#47)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [knip](https://knip.dev)
([source](https://redirect.github.com/webpro-nl/knip/tree/HEAD/packages/knip))
| [`5.33.1` ->
`5.34.0`](https://renovatebot.com/diffs/npm/knip/5.33.1/5.34.0) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/knip/5.34.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/knip/5.34.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/knip/5.33.1/5.34.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/knip/5.33.1/5.34.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>webpro-nl/knip (knip)</summary>

###
[`v5.34.0`](https://redirect.github.com/webpro-nl/knip/releases/tag/5.34.0)

[Compare
Source](https://redirect.github.com/webpro-nl/knip/compare/5.33.3...5.34.0)

- Don't use `path` if step also has `repository` in github-action plugin
([`c6e4d31`](https://redirect.github.com/webpro-nl/knip/commit/c6e4d310))
- Give plugins a chance to prep config args
([`a2217a2`](https://redirect.github.com/webpro-nl/knip/commit/a2217a28))
- Let's start out conservatively
([`a2e83f8`](https://redirect.github.com/webpro-nl/knip/commit/a2e83f88))
- More consistent naming
([`bae87d9`](https://redirect.github.com/webpro-nl/knip/commit/bae87d96))
- Optimize a bit after the dust has settled
([`31f1e7e`](https://redirect.github.com/webpro-nl/knip/commit/31f1e7ee))
- Cherry on the pie
([`617e067`](https://redirect.github.com/webpro-nl/knip/commit/617e067e))
- Handle config files only once across workspaces
([`939f511`](https://redirect.github.com/webpro-nl/knip/commit/939f5110))
- Improve naming and simplify a few things
([`f4db204`](https://redirect.github.com/webpro-nl/knip/commit/f4db2047))
- Add coverage for unused files with compiler extension
([`c2e2712`](https://redirect.github.com/webpro-nl/knip/commit/c2e27127))
- Ignore `virtual:` imports, don't report as unlisted dependencies
([`2ef75cc`](https://redirect.github.com/webpro-nl/knip/commit/2ef75ccf))
- Remove module resolving from plugins
([`53839e0`](https://redirect.github.com/webpro-nl/knip/commit/53839e08))
- Temp use Bun for in this integration test for green lights
([`98c1ff7`](https://redirect.github.com/webpro-nl/knip/commit/98c1ff7a))
- Add ability to add unresolved imports to `ignoreDependencies`
([`b8875be`](https://redirect.github.com/webpro-nl/knip/commit/b8875be3))
- Let's start out a tad more conservative
([`58ba79f`](https://redirect.github.com/webpro-nl/knip/commit/58ba79f9))
- Update dependencies
([`f4dc1e1`](https://redirect.github.com/webpro-nl/knip/commit/f4dc1e11))
- Optimize referenced dependency handling
([`a413ad8`](https://redirect.github.com/webpro-nl/knip/commit/a413ad84))
- Resolve config file paths and parse recursively
([`c03f963`](https://redirect.github.com/webpro-nl/knip/commit/c03f9630))
- Exclude empty config file path arrays from debug output
([`d288779`](https://redirect.github.com/webpro-nl/knip/commit/d288779e))
- Extend typedoc plugin
([`f2732fa`](https://redirect.github.com/webpro-nl/knip/commit/f2732fad))
- Presets are extended by local config in jest plugin
([`4973a9d`](https://redirect.github.com/webpro-nl/knip/commit/4973a9dc))
- Add test case to get refs from scripts
([`6115107`](https://redirect.github.com/webpro-nl/knip/commit/61151070))
- Refactor binary resolver & referenced dependency handling
([`f1349c2`](https://redirect.github.com/webpro-nl/knip/commit/f1349c23))

###
[`v5.33.3`](https://redirect.github.com/webpro-nl/knip/releases/tag/5.33.3)

[Compare
Source](https://redirect.github.com/webpro-nl/knip/compare/5.33.2...5.33.3)

- Add comment (close
[#&#8203;808](https://redirect.github.com/webpro-nl/knip/issues/808))
([`3dd6cfd`](https://redirect.github.com/webpro-nl/knip/commit/3dd6cfd0))
- Don't remove internally referenced bindingElement nodes
([#&#8203;808](https://redirect.github.com/webpro-nl/knip/issues/808))
([`307ef8d`](https://redirect.github.com/webpro-nl/knip/commit/307ef8df))
- Expand unused exports referenced in used exports
([#&#8203;808](https://redirect.github.com/webpro-nl/knip/issues/808))
([`1c04163`](https://redirect.github.com/webpro-nl/knip/commit/1c041635))
- Got tired of it
([`2f2a11e`](https://redirect.github.com/webpro-nl/knip/commit/2f2a11ea))
- Add test in new workspaces fixture for
[`3ee0476`](https://redirect.github.com/webpro-nl/knip/commit/3ee04761)
([`4a3f84c`](https://redirect.github.com/webpro-nl/knip/commit/4a3f84cd))
- Fix travis `isEnabled`
([`b6541f3`](https://redirect.github.com/webpro-nl/knip/commit/b6541f32))

###
[`v5.33.2`](https://redirect.github.com/webpro-nl/knip/releases/tag/5.33.2)

[Compare
Source](https://redirect.github.com/webpro-nl/knip/compare/5.33.1...5.33.2)

- Revert "Add/fix `getPluginEntryFilePatterns` helper" (resolves
[#&#8203;804](https://redirect.github.com/webpro-nl/knip/issues/804))
([`3ee0476`](https://redirect.github.com/webpro-nl/knip/commit/3ee04761))
- Add French article + order by date (recent first)
([`617a06a`](https://redirect.github.com/webpro-nl/knip/commit/617a06a1))
- Skip windows-latest (error: "The syntax of the command is incorrect")
([`aebbfb6`](https://redirect.github.com/webpro-nl/knip/commit/aebbfb64))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/marsidev/test-lib).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOC4xMzUuMiIsInVwZGF0ZWRJblZlciI6IjM4LjEzNS4yIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6WyJkZXBlbmRlbmNpZXMiXX0=-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>